GLOBAL_ENGAGE_RANGE = 70
SHIP_IMAGE_SCALE_FACTOR = 100
MOVE_RANGE_SCALE_FACTOR = 50
ICON_2D_SCALE_FACTOR = 0.2
TIME_ERROR_POPUP = 1.5
WING_AIM_FAC = (-5,5) #(normal, tangent) to wing aim vector
CAMERA_ZOOM_TIME = 1.3